# This file instructs Redocly's linter to ignore the rules contained for specific parts of your API.
# See https://redocly.com/docs/cli/ for more information.
api-specs/api-v1.yaml:
  info-license:
    - '#/info'
  no-server-example.com:
    - '#/servers/0/url'
  operation-operationId:
    - '#/paths/~1api~1v1~1hello/get/operationId'
    - '#/paths/~1api~1v1~1hello/post/operationId'
    - '#/paths/~1api~1v1~1goodbye/get/operationId'
  operation-4xx-response:
    - '#/paths/~1api~1v1~1hello/get/responses'
    - '#/paths/~1api~1v1~1hello/post/responses'
    - '#/paths/~1api~1v1~1goodbye/get/responses'
  security-defined:
    - '#/paths/~1api~1v1~1hello/get'
    - '#/paths/~1api~1v1~1hello/post'
    - '#/paths/~1api~1v1~1goodbye/get'
