openapi: 3.0.0
info:
  title: My API
  version: 1.0.0
  description: First API
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: http://localhost:3000
security: 
  - api_keys: []
paths:
  /api/v1/hello:
    get:
      summary: Returns a greeting message
      responses:
        200:
          description: A greeting message
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Hello World
        400:
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Bad request            
    post:
      summary: Returns a personalized greeting message
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: YourName
      responses:
        200:
          description: A personalized greeting message
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Hello YourName
        400:
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Bad request              
  /api/v1/goodbye:
    get:
      summary: Return goodbye message
      responses:
        200:
          description: Goodbye message.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Goodbye message.
                    example: Goodbye World
        400:
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Bad request              
components: 
  securitySchemes:
    api_keys:
      type: apiKey
      in: header
      name: X-API-Key