openapi: 3.0.0
info:
  title: My API
  version: 1.0.0
  description: First API
servers:
  - url: http://localhost:3000
paths:
  /api/v1/hello:
    get:
      summary: Returns a greeting message
      responses:
        200:
          description: A greeting message
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Hello World
    post:
      summary: Returns a personalized greeting message
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: YourName
      responses:
        200:
          description: A personalized greeting message
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Hello YourName
  /api/v1/goodbye:
    get:
      summary: Zwraca wiadomość pożegnalną
      responses:
        200:
          description: Wiadomość pożegnalna
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Wiadomość pożegnalna
                    example: Goodbye World
