name: Build and Deploy Docs

on: push
    # branches: [main]  # Ensure this matches your default branch name
    # paths:
    #   - 'api-specs/**'  # Ensure this matches the correct path
# permissions:
#   contents: write
jobs:
  lint-and-deploy:
    name: Test
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Checkout
        uses: actions/checkout@v4

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # # Install Redocly CLI
      # - name: Install Redocly CLI
      #   run: npm install -g @redocly/cli

      # # Lint OpenAPI spec
      # - name: Lint OpenAPI Spec
      #   run: redocly lint api-specs/api-v1.yaml  # Ensure this matches the correct path

      # # Build docs
      # - name: Build Docs
      #   run: |
      #     redocly bundle api-specs/api-v1.yaml --output docs/bundled-api-v1.yaml  # Ensure this matches the correct path
      #     # Optional: Generate HTML using Redoc
      #     redocly build-docs docs/bundled-api-v1.yaml --output docs/index.html  # Ensure this matches the correct path

      # Deploy to Netlify
      - name: Deploy to Netlify
        uses: netlify/actions/cli@v2
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=docs --prod