name: Build and Lint Docs

on: push

jobs:
  workflow:
    name: Test
    runs-on: ubuntu-latest
    steps:

      # Checkout code
      - name: Checkout
        uses: actions/checkout@v4

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install Redocly CLI
      - name: Install Redocly CLI
        run: npm install -g @redocly/cli

      # Lint OpenAPI spec
      - name: Lint OpenAPI Spec
        run: redocly lint api-specs/api-v1.yaml || exit 1

      # Build docs
      - name: Build Docs
        run: |
          mkdir -p docs
          redocly bundle api-specs/api-v1.yaml --output docs/bundled-api-v1.yaml || exit 1
          redocly build-docs docs/bundled-api-v1.yaml --output docs/index.html || exit 1

      # Verify Docs Output
      - name: Verify Docs Output
        run: |
          if [ ! -s docs/index.html ]; then
            echo "Error: Documentation build failed or output is empty."
            exit 1
          fi

      # Debugging step: List contents of docs directory
      - name: List Docs Directory
        run: ls -la docs

      # Upload artifact for GitHub Pages
      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs

      # # Deploy to GitHub Pages
      # - name: Deploy to GitHub Pages
      #   id: pages
      #   uses: actions/deploy-pages@v1
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
